In [6]:
import numpy as np
from tqdm import tqdm

SEGMENT_SIZE = 30
M_BINS = 30

DATABASES = ['AFDB', 'NSRDB', 'LTAFDB']

result = np.empty((0, M_BINS + 1))

for db in DATABASES:
    label = -1 if db == 'NSRDB' else 1
    
    rri_output = np.load(f"output/{db}.npy")
    np.random.shuffle(rri_output)

    rri_quantity = rri_output.shape[0]
    
    segments = np.empty((0, SEGMENT_SIZE))
    for i in range(0, rri_quantity, SEGMENT_SIZE):
        segment = rri_output[i:i+SEGMENT_SIZE]
        if (segment.shape[0] == SEGMENT_SIZE):
            segments = np.vstack((segments, segment))

    for segment in tqdm(segments):
        hist, _ = np.histogram(a=segment, range=(50, 2500), bins=M_BINS)
        x = hist
        y = label
        row = np.append(x, y)
        row = row.reshape((1, row.shape[0]))
        result = np.vstack((result, row))

np.save(f"output/v2/bins_{M_BINS}.npy", result)

100%|██████████| 103466/103466 [10:46<00:00, 159.95it/s]


In [33]:
rri_output_afdb = np.load(f"output/AFDB.npy")
print(f'AFDB {rri_output_afdb.shape[0]} RRIs')
rri_output_ltafdb = np.load(f"output/LTAFDB.npy")
print(f'LTAFDB {rri_output_ltafdb.shape[0]} RRIs')
rri_output_nsrdb = np.load(f"output/NSRDB.npy")
print(f'NSRDB {rri_output_nsrdb.shape[0]} RRIs')

AFDB 508116 RRIs
LTAFDB 3103986 RRIs
NSRDB 1806774 RRIs


In [37]:
rri_output_afdb[0:30]

array([552, 492, 416, 396, 436, 532, 568, 424, 296, 384, 328, 364, 388,
       360, 296, 340, 376, 364, 372, 492, 428, 572, 448, 632, 472, 464,
       420, 392, 400, 484])

In [36]:
rri_output_afdb = np.load(f"output/AFDB.npy")
print(f'AFDB {int(rri_output_afdb.shape[0]/30)} Segments')
rri_output_ltafdb = np.load(f"output/LTAFDB.npy")
print(f'LTAFDB {int(rri_output_ltafdb.shape[0]/30)} Segments')
rri_output_nsrdb = np.load(f"output/NSRDB.npy")
print(f'NSRDB {int(rri_output_nsrdb.shape[0]/30)} Segments')

AFDB 16937 Segments
LTAFDB 103466 Segments
NSRDB 60225 Segments


In [40]:
import numpy as np

bins = np.load(f"output/v2/bins_30.npy")
print(f'{bins.shape[0]} Segments')

180628 Segments


In [44]:
bins[bins[:,-1] == 1][0]

array([0., 0., 0., 0., 7., 4., 3., 7., 2., 2., 2., 1., 1., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.])

In [45]:
bins[bins[:,-1] == -1][0]

array([ 0.,  1.,  0.,  0.,  0.,  1.,  1.,  7.,  5.,  5.,  5.,  2.,  2.,
        0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0., -1.])

In [43]:
_

array([  50.        ,  131.66666667,  213.33333333,  295.        ,
        376.66666667,  458.33333333,  540.        ,  621.66666667,
        703.33333333,  785.        ,  866.66666667,  948.33333333,
       1030.        , 1111.66666667, 1193.33333333, 1275.        ,
       1356.66666667, 1438.33333333, 1520.        , 1601.66666667,
       1683.33333333, 1765.        , 1846.66666667, 1928.33333333,
       2010.        , 2091.66666667, 2173.33333333, 2255.        ,
       2336.66666667, 2418.33333333, 2500.        ])